# Generated by Django 5.1 on 2025-08-01 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_receipe_recipee_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='recipee_view',
            new_name='receipe_view_count',
        ),
    ]
